export const FEATURE_CONFIGS = [
  {
    name: 'age',
    label: 'Age',
    unit: 'years',
    type: 'number',
    min: 18,
    max: 100,
    step: 1,
    default: '',
    description: 'Patient age in completed years',
    section: 'demographics',
  },
  {
    name: 'sex',
    label: 'Biological Sex',
    type: 'select',
    options: [
      { label: 'Select…', value: '' },
      { label: 'Female (0)', value: 0 },
      { label: 'Male (1)', value: 1 },
    ],
    default: '',
    description: 'Biological sex at birth',
    section: 'demographics',
  },
  {
    name: 'cp',
    label: 'Chest Pain Type',
    type: 'select',
    options: [
      { label: 'Select…', value: '' },
      { label: '0 — Typical Angina', value: 0 },
      { label: '1 — Atypical Angina', value: 1 },
      { label: '2 — Non-Anginal Pain', value: 2 },
      { label: '3 — Asymptomatic', value: 3 },
    ],
    default: '',
    description: 'Clinical symptomatic classification of chest pain',
    section: 'symptoms',
  },
  {
    name: 'trestbps',
    label: 'Resting Blood Pressure',
    unit: 'mmHg',
    type: 'number',
    min: 80,
    max: 220,
    step: 1,
    default: '',
    description: 'Resting systolic blood pressure upon admission',
    section: 'vitals',
  },
  {
    name: 'chol',
    label: 'Serum Cholesterol',
    unit: 'mg/dl',
    type: 'number',
    min: 100,
    max: 550,
    step: 1,
    default: '',
    description: 'Total fasting serum cholesterol measurement',
    section: 'vitals',
  },
  {
    name: 'fbs',
    label: 'Fasting Blood Sugar',
    type: 'select',
    options: [
      { label: 'Select…', value: '' },
      { label: 'Normal (< 120 mg/dl)', value: 0 },
      { label: 'Elevated (> 120 mg/dl)', value: 1 },
    ],
    default: '',
    description: 'Fasting blood glucose marker (>120 mg/dl is diabetic range)',
    section: 'vitals',
  },
  {
    name: 'restecg',
    label: 'Resting ECG Result',
    type: 'select',
    options: [
      { label: 'Select…', value: '' },
      { label: '0 — Normal', value: 0 },
      { label: '1 — ST-T Wave Abnormality', value: 1 },
      { label: '2 — Left Ventricular Hypertrophy', value: 2 },
    ],
    default: '',
    description: '12-lead electrocardiographic evaluation at rest',
    section: 'diagnostics',
  },
  {
    name: 'thalach',
    label: 'Max Heart Rate Achieved',
    unit: 'bpm',
    type: 'number',
    min: 60,
    max: 220,
    step: 1,
    default: '',
    description: 'Peak heart rate recorded during exercise treadmill test',
    section: 'vitals',
  },
  {
    name: 'exang',
    label: 'Exercise-Induced Angina',
    type: 'select',
    options: [
      { label: 'Select…', value: '' },
      { label: 'No (0)', value: 0 },
      { label: 'Yes (1)', value: 1 },
    ],
    default: '',
    description: 'Occurrence of angina symptoms under physical exertion',
    section: 'symptoms',
  },
  {
    name: 'oldpeak',
    label: 'ST Depression (Oldpeak)',
    unit: 'mm',
    type: 'number',
    min: 0.0,
    max: 6.5,
    step: 0.1,
    default: '',
    description: 'ST depression induced by exercise relative to rest',
    section: 'diagnostics',
  },
  {
    name: 'slope',
    label: 'Peak Exercise ST Slope',
    type: 'select',
    options: [
      { label: 'Select…', value: '' },
      { label: '0 — Upsloping', value: 0 },
      { label: '1 — Flat', value: 1 },
      { label: '2 — Downsloping', value: 2 },
    ],
    default: '',
    description: 'Slope of the peak exercise ST segment',
    section: 'diagnostics',
  },
  {
    name: 'ca',
    label: 'Major Vessels (0–3)',
    type: 'select',
    options: [
      { label: 'Select…', value: '' },
      { label: '0 Vessels Colored', value: 0 },
      { label: '1 Vessel Colored', value: 1 },
      { label: '2 Vessels Colored', value: 2 },
      { label: '3 Vessels Colored', value: 3 },
    ],
    default: '',
    description: 'Number of major vessels (0-3) colored by fluoroscopy',
    section: 'diagnostics',
  },
  {
    name: 'thal',
    label: 'Thalassemia / Perfusion',
    type: 'select',
    options: [
      { label: 'Select…', value: '' },
      { label: '1 — Normal Perfusion', value: 1 },
      { label: '2 — Fixed Defect', value: 2 },
      { label: '3 — Reversible Defect', value: 3 },
    ],
    default: '',
    description: 'Nuclear scintigraphy or cardiac perfusion defect classification',
    section: 'diagnostics',
  },
];

export const FEATURE_LABELS = {
  age: 'Age (years)',
  sex: 'Biological Sex',
  cp: 'Chest Pain Type',
  trestbps: 'Resting Blood Pressure (mmHg)',
  chol: 'Serum Cholesterol (mg/dl)',
  fbs: 'Fasting Blood Sugar',
  restecg: 'Resting ECG Result',
  thalach: 'Maximum Heart Rate (bpm)',
  exang: 'Exercise-Induced Angina',
  oldpeak: 'ST Depression (oldpeak)',
  slope: 'ST Segment Slope',
  ca: 'Major Vessels (0-3)',
  thal: 'Thalassemia Type',
};

export const SAMPLE_PRESETS = [
  {
    id: 'preset-healthy',
    title: 'Healthy / Low Risk',
    description: 'Asymptomatic 45yo, normal BP, clear vessels',
    data: {
      age: 45,
      sex: 0,
      cp: 3,
      trestbps: 115,
      chol: 185,
      fbs: 0,
      restecg: 0,
      thalach: 172,
      exang: 0,
      oldpeak: 0.0,
      slope: 0,
      ca: 0,
      thal: 1,
    },
  },
  {
    id: 'preset-elevated',
    title: 'High Risk / Symptomatic',
    description: '62yo male, typical angina, hypertension, vessel stenosis',
    data: {
      age: 62,
      sex: 1,
      cp: 0,
      trestbps: 148,
      chol: 285,
      fbs: 1,
      restecg: 2,
      thalach: 125,
      exang: 1,
      oldpeak: 2.6,
      slope: 2,
      ca: 2,
      thal: 3,
    },
  },
  {
    id: 'preset-borderline',
    title: 'Borderline / Intermediate',
    description: '55yo male, non-anginal pain, elevated cholesterol',
    data: {
      age: 55,
      sex: 1,
      cp: 2,
      trestbps: 132,
      chol: 246,
      fbs: 0,
      restecg: 1,
      thalach: 148,
      exang: 0,
      oldpeak: 1.0,
      slope: 1,
      ca: 0,
      thal: 2,
    },
  },
];

export const SHAP_ADVICE = {
  age: {
    title: 'Age Biomarker',
    context: 'Advanced age increases physiological cardiovascular vulnerability.',
    advice: 'Recommend annual comprehensive cardiology reviews, vascular screening, and blood pressure monitoring.',
  },
  sex: {
    title: 'Biological Sex',
    context: 'Biological sex influences cardiovascular risk distribution.',
    advice: 'Monitor baseline arterial health and lipid ratios from age 40 onward.',
  },
  cp: {
    title: 'Chest Pain Type',
    context: 'Typical or atypical angina is an active indicator of myocardial ischemia.',
    advice: 'Formal stress electrocardiography and clinical cardiology evaluation are indicated.',
  },
  trestbps: {
    title: 'Resting Blood Pressure',
    context: 'Elevated resting blood pressure strains the ventricular myocardium and arterial walls.',
    advice: 'Target systolic BP < 120 mmHg via sodium restriction, regular aerobic activity, and physician-guided therapy.',
  },
  chol: {
    title: 'Serum Cholesterol',
    context: 'Elevated total cholesterol promotes atherosclerotic plaque progression.',
    advice: 'Target total cholesterol < 200 mg/dl. Consider lipid-lowering therapy if lifestyle modifications are insufficient.',
  },
  fbs: {
    title: 'Fasting Blood Sugar',
    context: 'Fasting glucose > 120 mg/dl indicates impaired metabolic or diabetic regulation.',
    advice: 'Maintain regular HbA1c screening every 3–6 months and strict glycemic control.',
  },
  restecg: {
    title: 'Resting ECG Result',
    context: 'Abnormal resting electrical conduction suggests underlying structural or ischemic disease.',
    advice: 'Follow up with an echocardiogram or 24-hour Holter monitor to assess ventricular wall motion.',
  },
  thalach: {
    title: 'Maximum Heart Rate',
    context: 'Lower peak exertion heart rate may indicate reduced chronotropic reserve.',
    advice: 'Consider structured aerobic conditioning and supervised exercise testing.',
  },
  exang: {
    title: 'Exercise-Induced Angina',
    context: 'Exertional chest discomfort indicates reduced coronary perfusion during demand.',
    advice: 'Avoid unsupervised high-intensity exertion; arrange coronary artery evaluation (e.g. CTA).',
  },
  oldpeak: {
    title: 'ST Depression',
    context: 'Significant ST depression (>1.0 mm) reflects exercise-induced myocardial ischemia.',
    advice: 'Prompt formal cardiology consultation and comprehensive non-invasive imaging are advised.',
  },
  slope: {
    title: 'ST Segment Slope',
    context: 'Flat or downsloping ST segments during peak exertion correlate with coronary disease.',
    advice: 'Correlate with myocardial perfusion imaging or coronary angiography.',
  },
  ca: {
    title: 'Major Vessels Colored',
    context: 'Visualized major vessel involvement correlates strongly with multivessel disease.',
    advice: 'Interventional cardiology consultation (PCI/CABG evaluation) is indicated for >=1 blocked vessel.',
  },
  thal: {
    title: 'Thalassemia / Defect',
    context: 'Perfusion defects (fixed or reversible) indicate myocardial compromise.',
    advice: 'Reversible defects suggest salvageable ischemic myocardium; fixed defects suggest prior infarction.',
  },
};
